# Generated by Django 4.0.3 on 2022-04-13 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entregable',
            new_name='Entregables',
        ),
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='Estudiantes',
        ),
    ]
